data_paths:
  charges: "C:\\Users\\krsai\\PycharmProjects\\Car-Crash-PySpark\\data\\Charges_use.csv"
  endorsements: "C:\\Users\\krsai\\PycharmProjects\\Car-Crash-PySpark\\data\\Endorse_use.csv"
  restrict: "C:\\Users\\krsai\\PycharmProjects\\Car-Crash-PySpark\\data\\Restrict_use.csv"
  damages: "C:\\Users\\krsai\\PycharmProjects\\Car-Crash-PySpark\\data\\Damages_use.csv"
  primary_person: "C:\\Users\\krsai\\PycharmProjects\\Car-Crash-PySpark\\data\\Primary_Person_use.csv"
  units: "C:\\Users\\krsai\\PycharmProjects\\Car-Crash-PySpark\\data\\Units_use.csv"

output_paths:
  analytics_results: "C:\\Users\\krsai\\PycharmProjects\\Car-Crash-PySpark\\output\\"
