data_paths:
  charges: "../data/Charges_use.csv"
  endorsements: "../data/Endorse_use.csv"
  restrict: "../data/Restrict_use.csv"
  damages: "../data/Damages_use.csv"
  primary_person: "../data/Primary_Person_use.csv"
  units: "../data/Units_use.csv"

output_paths:
  analytics_results: "../output/"
